RedditClone/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedditClone.Models;
using Microsoft.AspNet.Identity;

namespace RedditClone.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.Title = "What's Hot";
            var db = new ApplicationDbContext();
            var posts = db.Posts.OrderByDescending(o=>o.DatePosted).ToList();
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.UserId = User.Identity.GetUserId();
            }
            return View(posts);
        }
    }
}

RedditClone/Controllers/RedditPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RedditClone.Models;
using Microsoft.AspNet.Identity;

namespace RedditClone.Controllers
{
    public class RedditPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RedditPosts
        public ActionResult Index()
        {
            ViewBag.Title = "What's Hot";
            var db = new ApplicationDbContext();
            var posts = db.Posts.ToList();
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.UserId = User.Identity.GetUserId();
            }
            return View(posts);
        }

        // GET: RedditPosts/Details/5
        public ActionResult Details(string UserId)
        {
            if (UserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RedditPost redditPost = db.Posts.Find(UserId);
            if (redditPost == null)
            {
                return HttpNotFound();
            }
            return View(redditPost);
        }

        // GET: RedditPosts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RedditPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,UpVotes,DownVotes,DatePosted,Img")] RedditPost redditPost)
        {
            if (ModelState.IsValid)
            {
                redditPost.UserId = HttpContext.User.Identity.GetUserId();
                db.Posts.Add(redditPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(redditPost);
        }

        // GET: RedditPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RedditPost redditPost = db.Posts.Find(id);
            if (redditPost == null)
            {
                return HttpNotFound();
            }
            return View(redditPost);
        }

        // POST: RedditPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,UpVotes,DownVotes,DatePosted,Img")] RedditPost redditPost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(redditPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(redditPost);
        }

        // GET: RedditPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RedditPost redditPost = db.Posts.Find(id);
            if (redditPost == null)
            {
                return HttpNotFound();
            }
            return View(redditPost);
        }

        // POST: RedditPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RedditPost redditPost = db.Posts.Find(id);
            db.Posts.Remove(redditPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RedditClone/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RedditClone/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RedditClone/Views/Home/Index.cshtml
@model IEnumerable<RedditClone.Models.RedditPost>
@using Microsoft.AspNet.Identity
@using RedditClone.Models
@using RedditClone.ViewModels

@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-sm-8 table-bordered table-striped">
        @foreach (var post in Model)
        {
            <br />
            <div class="media col-sm-2">
                <div class="media-left media-middle" id="voteBox-@post.Id">        
                    @Html.Partial("_voteDisplay", post)
                </div>
            </div>
            <div class="media-left media-middle">
                <img class="media-object" height="80" src="~/Images/elle.jpg" alt="..." />
            </div>
                <div class="media-body">
                    <a href="~/Views/RedditPosts/Details.cshtml/@post.Id">
                        <h4 class="media-heading">@post.Title</h4>
                    </a>
                    <div>
                        submitted&emsp;<span>
                            @post.DatePosted.ToShortDateString()
                        </span>&emsp;by&emsp;<span>@post.User.UserName</span>
                    </div>
                    <div>
                        @post.Body
                    </div>
                    <div>
                        <a>@post.Comments.Count()</a>
                        <a><span>comments</span></a>
                        <span>@Html.ActionLink("Share", "Share", "RedditPosts")</span>
                    </div>
                </div>
        }
    </div>


    <br />
    @if (!HttpContext.Current.User.Identity.IsAuthenticated)
    {
        <div class="col-sm-4 table-bordered">
            <br />
            @*@using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {*@
            @*@Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

            @*@Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })*@

            <input name="username" placeholder="username" id="username" size="10" />
            <label for="username" class="hidden">Username</label>

            @*@Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })*@

            <input name="password" placeholder="password" id="password" size="10" />
            <label for="password" class="hidden">Password</label>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        @*@Html.CheckBoxFor(m => m.LoginVM.RememberMe)
                            @Html.LabelFor(m => m.LoginVM.RememberMe)*@
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <input type="submit" value="login" />
            </div>
            @*}*@
            <br />
        </div>
    }
    <div class="btn-lg col-sm-4">
        @if (HttpContext.Current.User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("New Post", "Create", "RedditPosts")
        }

    </div>
</div>